[package]
name = "passphrase_generator"
version = "0.1.2"
authors = ["Davide Giovannini <giovannini.davide90@gmail.com>"]
edition = "2021"

[dependencies]
rand = "0.8"
structopt = "0.3"
structopt-derive = "0.4"
