[package]
name = "passphrase_generator"
version = "0.1.1"
authors = ["Davide Giovannini <giovannini.davide90@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
structopt = "0.2"
structopt-derive = "0.2"
